ARG BASE_IMGAGE=ghcr.io/celestiaorg/explorer-base:latest
FROM ${BASE_IMGAGE}
WORKDIR /app

COPY . ./
#COPY ping.conf /etc/nginx/conf.d/default.conf
COPY ping.conf /etc/nginx/sites-available/default
COPY  docker/entrypoint.sh /opt/entrypoint.sh

RUN rm -rf src/chains/mainnet/* &&\
    rm -rf src/chains/testnet/* &&\
    rm -rf /var/lib/apt/lists;

EXPOSE 80

STOPSIGNAL SIGQUIT

ENTRYPOINT ["/bin/bash", "/opt/entrypoint.sh"]
